Navy 207
LiveIntent/live-connect pull request #53
Opened 2021-11-03 13:09 UTC by melgenek

Short description if any.

Author Todo List:

- [ ] Add/adjust tests (if applicable)
- [ ] Build in CI passes
- [ ] Latest master revision is merged into the branch
- [ ] Self-Review
- [ ] Set `Ready For Review` status

2021-11-03 15:19 UTC, melgenek commented on src/idex/identity-resolver.js
> +function _cacheKey (additionalParams) {
this is the only thing that is needed to make the cache work for different params.
Everything else is fixing the linting and making the storage handler generic.

2021-11-04 12:59 UTC, 3link requested changes

2021-11-04 12:59 UTC, 3link commented on src/handlers/storage-handler.js
> +          if (oldLsExpirationEntry && Date.parse(oldLsExpirationEntry) <= new Date().getTime()) {
This will always expire entries.

2021-11-04 13:00 UTC, 3link commented on src/handlers/storage-handler.js
> +          if (oldLsExpirationEntry && Date.parse(oldLsExpirationEntry) <= new Date().getTime()) {
Never mind, misread it.

2021-11-04 16:19 UTC, 3link requested changes

2021-11-04 16:23 UTC, melgenek commented on src/idex/identity-resolver.js
>        console.error('Error storing response to cookies', ex)
https://github.com/LiveIntent/live-connect/pull/53/commits/7a72beb052d4332a7ea383953200d44feb8ce20f#diff-a57fbdfbf75933739497179697efad2140acc7c7d05c6cd3249b76646e5b7592L36

2021-11-04 16:23 UTC, melgenek commented on src/idex/identity-resolver.js
> +      const storedCookie = storageHandler.get(_cacheKey(additionalParams))
https://github.com/LiveIntent/live-connect/pull/53/commits/7a72beb052d4332a7ea383953200d44feb8ce20f#diff-a57fbdfbf75933739497179697efad2140acc7c7d05c6cd3249b76646e5b7592R74

2021-11-04 16:25 UTC, 3link commented on src/manager/identifiers.js
> +        emitter.error('CookieLsGetOrAdd', 'Failed manipulating cookie jar or ls', e)
I see.

2021-11-04 16:30 UTC, 3link approved these changes

2021-11-08 12:10 UTC, merged